[tool.black]
line-length = 80
py36 = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | local_settings\.py
  | data_warehouse\/settings
)/
'''
