version: 2
jobs:
  build:
    working_directory: ~/bulk-api-python-client
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ checksum "setup.py" }}
      - run:
          command: |
            sudo pip install -e .[dev]
      - save_cache:
          key: deps9-{{ checksum "setup.py" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |
            pytest
      - run:
          command: |
            pycodestyle

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
