version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
    automerged_updates:
      - match:
          update_type: "semver:minor"
